### ISSUE TITLE
Testing that PING

### ISSUE THREAD

**Issue by Rizier123** [Rizier123/hello-world-RENAME#6]
@ArcticEcho

Does this work?

**Comment by ArcticEcho** [comment]
Yes, yes it does.

**Comment by Rizier123** [comment]
O_o ping me, back. Want to see where I get the notifications.

**Comment by ArcticEcho** [comment]
@Rizier123  Ok.

**Comment by Rizier123** [comment]
Issue solved thanks @ArcticEcho  for your help :palm_tree:

**Comment by ArcticEcho** [comment]
Np
